const assert=require('node:assert/strict');
const summarize=require('../dist/history-summary.js');
const grader=require('../dist/grading.js');
globalThis.window=globalThis;require('../dist/data.js');require('../dist/pm-data.js');require('../dist/archive-data.js');
const exam={year:2025},am=globalThis.EXAM,fields=globalThis.PM_FIELDS;
const p={am:{answers:Array(25).fill(null),checked:Array(25).fill(false)},pm:{pm1:{answers:{},checked:{},manual:{},scores:{}},pm2:{answers:{},checked:{},manual:{},scores:{}}}};
assert.equal(summarize(null,exam,am,fields,grader).hasActivity,false);
p.am.answers[0]=am[0].answer;
let s=summarize(p,exam,am,fields,grader);assert.equal(s.morning.answered,1);assert.equal(s.morning.correct,0);assert.equal(s.morning.graded,0);
p.am.checked[0]=true;p.am.answers[1]=['ア','イ','ウ','エ'].find(a=>a!==am[1].answer);p.am.checked[1]=true;
p.pm.pm1.scores[1]=0;
s=summarize(p,exam,am,fields,grader);assert.equal(s.morning.correct,1);assert.equal(s.morning.graded,2);assert.equal(s.afternoon[0].score,0);assert.equal(s.afternoon[1].score,null);
const manual=fields['pm1-1'].find(f=>f.kind==='manual'),key='1:'+manual.id;
p.pm.pm1.answers[key]='照合用メモ';p.pm.pm1.checked[key]=true;p.pm.pm1.manual[key]='correct';
s=summarize(p,exam,am,fields,grader);assert.equal(s.afternoon[0].selfCorrect,1);assert.equal(s.afternoon[0].correct,0);
const old=globalThis.EXAM_ARCHIVE[2024],column=old.fields['pm1-1'].find(f=>f.section===1&&f.label==='b');
const older=structuredClone(p);older.pm.pm1={answers:{['1:'+column.id]:'選択肢＃、設問＃'},checked:{['1:'+column.id]:true},manual:{},scores:{}};
s=summarize(older,old,old.am,old.fields,grader);assert.equal(s.afternoon[0].correct,1);
assert.equal(summarize(null,exam,am,fields,grader).hasActivity,false);
console.log('PASS: history excludes ungraded answers, retains zero scores, separates self-assessment, and grades archive columns.');
